The code example are modified from below source to confirm my understanding.  
Source: [José Unpingco, Python for Probability, Statistics, and Machine Learning](https://www.amazon.com/Python-Probability-Statistics-Machine-Learning/dp/3319307150)

In [1]:
import numpy as np
import time

# NumPy Arrays

In [2]:
x = np.array([1, 2, 3])

In [3]:
x

array([1, 2, 3])

In [4]:
#The itemize property shows the number of bytes per item.
x.itemsize

8

### processing arrays element-wise without additional looping semantics

In [5]:
def custom_timeit(method):
    def timed(*args, **kwargs):
        t1 = time.time()
        result = method(*args, **kwargs)
        t2 = time.time()
        print("{0}: {1} sec".format(method.__name__, t2-t1))
        return result
    return timed

In [6]:
lst = np.random.uniform(-1, 1, size=10**4)

In [7]:
@custom_timeit
def numpy_op(iterable):
    return np.sin(iterable, dtype=np.float32)

In [8]:
@custom_timeit
def math_module_op(iterable):
    from math import sin 
    return [sin(i) for i in iterable]

In [9]:
res_numpy = numpy_op(lst);

numpy_op: 0.002410888671875 sec


In [10]:
res_math = math_module_op(lst);

math_module_op: 0.011237382888793945 sec


### dimensions

In [11]:
x=np.array([[1,2,3], [4,5,6]])

In [12]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x.shape

(2, 3)

In [14]:
x[:, 0]

array([1, 4])

In [15]:
x[:, 1]

array([2, 5])

In [16]:
x[0, :]

array([1, 2, 3])

In [17]:
x[1, :]

array([4, 5, 6])

In [18]:
x[:, 1:] # all rows, 1st thru last column

array([[2, 3],
       [5, 6]])

In [19]:
x[:, ::2] # all rows, every other column

array([[1, 3],
       [4, 6]])

In [20]:
x[:, ::-1] # reverse order of columns

array([[3, 2, 1],
       [6, 5, 4]])

### NumPy Array Memory

Numpy uses pass-by-reference semantics so that slice operations are views into the array without implicit copying.
=> slicing creates views (no copying) and advanced indexing creates copies.  

if you want to explicitly force a copy without any indexing tricks, you can do y = x.copy()
or you can also do index by integer list to force copy

In [21]:
x = np.ones((3, 3))

In [22]:
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [23]:
x[:, [0,1,2,2]] # notice duplicated last dimension

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [24]:
y = x[:, [0,1,2,2]] # same as above, but do assign it to y
y

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [25]:
x[0, 0] = 999 #change element in x
x

array([[ 999.,    1.,    1.],
       [   1.,    1.,    1.],
       [   1.,    1.,    1.]])

In [26]:
y # not changed!

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [27]:
p = np.ones((3, 3))

In [28]:
q = p[:2, :2] # view of upper left piece

In [29]:
p[0, 0] = 999 # change value
p

array([[ 999.,    1.,    1.],
       [   1.,    1.,    1.],
       [   1.,    1.,    1.]])

In [30]:
q # changed y also!

array([[ 999.,    1.],
       [   1.,    1.]])

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
b = a[[0, 1, 2]]
b

array([0, 1, 2])

In [33]:
c = a[:3]
c

array([0, 1, 2])

In [34]:
np.all(b == c)

True

In [35]:
a[0] = 999
a

array([999,   1,   2,   3,   4])

In [36]:
b # b is unaffeted. b is a copy, created by integer list index to force copy

array([0, 1, 2])

In [37]:
c # c is affected. c is a view

array([999,   1,   2])

# NumPy Matrices

In [38]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [39]:
x = np.matrix([[1],[0],[0]])
x

matrix([[1],
        [0],
        [0]])

In [40]:
a * x # row-column matrix multiplication

matrix([[1],
        [4],
        [7]])

In [41]:
a.dot(x) #same op

matrix([[1],
        [4],
        [7]])

In [42]:
c = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
np.multiply(a, c) # elementwise multiplication,

matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [44]:
#It is unnecessary to cast everything to matrices for multiplication


In [45]:
m = np.ones((3, 3))
m

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [46]:
type(m)

numpy.ndarray

In [47]:
n = np.ones((3, 1))
n

array([[ 1.],
       [ 1.],
       [ 1.]])

In [48]:
type(n)

numpy.ndarray

In [49]:
m * n # not a row-column multiplication

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [50]:
type(m * n)

numpy.ndarray

In [51]:
r = np.full((3, 1), 10, dtype=np.float32)
r

array([[ 10.],
       [ 10.],
       [ 10.]], dtype=float32)

In [52]:
m * r # not a row-column multiplication

array([[ 10.,  10.,  10.],
       [ 10.,  10.,  10.],
       [ 10.,  10.,  10.]])

In [53]:
np.matrix(m) * n # row-column multiplication

matrix([[ 3.],
        [ 3.],
        [ 3.]])

In [54]:
np.matrix(m) * r # row-column multiplication

matrix([[ 30.],
        [ 30.],
        [ 30.]])

# NumPy Broadcasting

In [55]:
x = np.array([0,1])
x

array([0, 1])

In [56]:
y = np.array([0,1])
y

array([0, 1])

In [57]:
"""
# add broadcast dimension: 
make copies of y along this dimension to create a conformable calculation
"""
x + y[:, None] # add broadcast dimension:

array([[0, 1],
       [1, 2]])

In [58]:
p = np.array([0,1])
p

array([0, 1])

In [59]:
q = np.array([0,1,2])
q

array([0, 1, 2])

In [60]:
p + q[:, None]

array([[0, 1],
       [1, 2],
       [2, 3]])

In [61]:
p[:, None] + q

array([[0, 1, 2],
       [1, 2, 3]])

In [62]:
i = np.array([0, 1])
i

array([0, 1])

In [63]:
j = np.array([0,1,2])
j

array([0, 1, 2])

In [64]:
k = np.array([0,1,2,3])
k

array([0, 1, 2, 3])

In [65]:
i + j[:, None]

array([[0, 1],
       [1, 2],
       [2, 3]])

In [66]:
i + j[:, None] + k[:, None, None]

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]],

       [[3, 4],
        [4, 5],
        [5, 6]]])

# NumPy Masked Arrays

In [67]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
y = np.ma.masked_array(x, x < 5)
y

masked_array(data = [-- -- -- -- -- 5 6 7 8 9],
             mask = [ True  True  True  True  True False False False False False],
       fill_value = 999999)

In [69]:
print(y)

[-- -- -- -- -- 5 6 7 8 9]


In [70]:
 print(y.shape) # (10,): the size of the array remains the same

(10,)


In [71]:
z = x[x < 5]

In [72]:
print(z)

[0 1 2 3 4]


In [73]:
print(z.shape) # (5,)

(5,)
